# Generated by Django 4.2.5 on 2023-10-01 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EpicEvents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
